version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=yolotestdatabase
      - MYSQL_USER=joon_admin
      - MYSQL_PASSWORD=DevUser123!#
    healthcheck:
      test: 'exit 0'
    ports:
      - '127.0.0.1:3316:3306/tcp'

  be:
    build: .
    depends_on:
      - db
    ports:
      - '8080:8080'
      - '9229:9229'
    command: ['./docker_entrypoint.sh']
